remote_theme             : "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

encoding: UTF-8
locale: "en-US"
title: Ryan
description: A simple website for a human.
url: "https://ryanharper.net"
repository: "noyhrynban/noyhrynban.github.io"

$intro-transition  : none;

plugins:
  - jekyll-include-cache

github: [metadata]

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-137252593-1"
    anonymize_ip: false # default

twitter:
  username: &twitter "noyhrynban"
og_image: /assets/images/bio-photo.webp # minimum size of 120px by 120px, and less than 1MB
social:
  type: Person # Person or Organization (defaults to Person)
  name: Ryan Harper # If the user or organization name differs from the site's name
  links:
    - "https://instagram.com/noyhrynban"
    - "https://www.linkedin.com/in/noyhrynban"
    - "https://github.com/noyhrynban/"
    - "https://twitter.com/noyhrynban"

social_links: &social_links
  - label: "Instagram"
    icon: "fab fa-fw fa-instagram"
    url: "https://instagram.com/noyhrynban"
  - label: "LinkedIn"
    icon: "fab fa-fw fa-linkedin"
    url: "https://linkedin.com/in/noyhrynban"
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/noyhrynban"
  - label: "Twitter"
    icon: "fab fa-fw fa-twitter"
    url: "https://twitter.com/noyhrynban"

author:
  name: Ryan Harper
  avatar: "/assets/images/bio-photo.webp"
  bio: One medium-sized nerd
  location: Los Angeles, California
  links: *social_links

# Reading Files
include: 
  - _pages
exclude:
  - .DS_Store

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: false
  # _photo albums
  - scope:
      path: "assets/images/photo_albums"
    values:
      album: true

collections_dir: collections
collections:
  - photo_albums

footer:
  links: *social_links
